---
# tasks file for apache2

- name: apt-get update
  apt: update_cache=yes cache_valid_time=3600
  tags: apache2

- name: apt-get purge
  apt: name={{ item }} state=absent purge=yes
  with_items:
    - apache2-mpm-event
    - apache2-mpm-itk
    - apache2-mpm-worker
  tags: apache2

- name: apt-get install
  apt: name={{ item }} state=latest
  with_items:
    - apache2
    - apache2-doc
    - apache2-mpm-prefork
    - apache2-suexec-custom
    - apache2-utils
    - libapache2-mod-fcgid
    - libapache2-mod-rpaf
  tags: apache2

- name: enable module
  apache2_module: name={{ item }} state=present
  with_items:
    - actions
    - alias
    - auth_basic
    - auth_digest
    - authn_core
    - authn_file
    - authz_core
    - authz_host
    - authz_user
    - autoindex
    - deflate
    - expires
    - fcgid
    - filter
    - mime
    - mpm_prefork
    - negotiation
    - proxy
    - proxy_http
    - rewrite
    - rpaf
    - ssl
    - status
    - suexec
  tags: apache2

- name: enable service
  service: name=apache2 enabled=yes
  notify: restart apache2
  tags: apache2
