---
# tasks file for hswong3i.apache2_vhosts

- name: create group
  group:
    name: "{{ apache2_vhosts_user }}"
    gid: "{{ apache2_vhosts_gid | default(None) or omit }}"
  notify: restart apache2
  tags: hswong3i.apache2_vhosts

- name: create user
  user:
    name: "{{ apache2_vhosts_user }}"
    password: "{{ apache2_vhosts_pass | password_hash('sha512', apache2_vhosts_hash_salt) }}"
    home: "{{ apache2_vhosts_home }}"
    group: "{{ apache2_vhosts_user }}"
    uid: "{{ apache2_vhosts_uid | default(None) or omit }}"
    shell: "/bin/bash"
  when: apache2_vhosts_document_root is string
  notify: restart apache2
  tags: hswong3i.apache2_vhosts

- name: prepare file
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: "{{ item.state }}"
  with_items:
    - { path: "{{ apache2_vhosts_document_root }}", owner: "{{ apache2_vhosts_user }}", group: "{{ apache2_vhosts_user }}", mode: "0755", state: "directory" }
  when: apache2_vhosts_document_root is string
  notify: restart apache2
  tags: hswong3i.apache2_vhosts

- name: copy templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: "etc/apache2/sites-available/default.conf.j2", dest: "/etc/apache2/sites-available/{{ apache2_vhosts_server_name }}.conf", owner: "root", group: "root", mode: "0644" }
  notify: restart apache2
  tags: hswong3i.apache2_vhosts

- name: a2ensite
  file:
    path: "/etc/apache2/sites-enabled/{{ apache2_vhosts_server_name }}.conf"
    src: "../sites-available/{{ apache2_vhosts_server_name }}.conf"
    state: link
  notify: restart apache2
  tags: hswong3i.apache2_vhosts
